version: '3'

services:
  web:
    container_name: popup2-9
    image: nginx:alpine
    ports:
      - "9989:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    restart: unless-stopped
